### PR TITLE
add "pos" subcommand

### PR DESCRIPTION
**Pull request by lolbinarycat**
i basically just wrote this the same way i would if i was writing C, hope that's ok.

the description of the new subcommand doesn't show up with --help for some reason

also emacs might have fucked up the formatting, sorry.

### CODE REVIEW

**Comment by Qyriad** [comment]
Looks pretty good, just a few things. First is that this doesn't print anything if it has no position information, like `xil pos -CE '{ pkgs }: pkgs.lib'`. Second is that there's nothing in the `--help` for the `pos` subcommand itself (as in, `xil --help` has no description for `pos`). And lastly, and this one is very subjective, but maybe move the actual path and position to its own line for ease of copying?

After those would be happy to merge 🙂

**Comment by lolbinarycat** [comment]
i was originally also going to hook into unsafeGetAttrPos, but it turns out that's a lot harder when you're operating on values instead of unparsed strings.  now that it's only ever printing a single best-effort guess (except in the case where a derivation has a __functor attribute, i suppose), i think i'm going to have it output just the path, so it can easily be piped into wl-copy or xclip.

**Comment by lolbinarycat** [comment]
@Qyriad added an error message and simplified the output :3

**Review by Qyriad — APPROVED** [review]

**Comment by Qyriad** [comment]
Hey, hey github, you're supposed to consider a PR merged if I push something with that message. Fuck off.

Anyway, thank you for this! I have squashed it and manually merged it as 835beb07f4f91dfa1060534b0428981c1472a67d!

**Pull request closed without merging**
